name: Source trigger pauling
run-name: Source trigger pauling from ${{ vars.SRC_REPOSITORY }}

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'
jobs:
  check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.add-and-commit.outputs.committed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get latest commit hash
        env:
          REPO: ${{ vars.SRC_REPOSITORY }}
          BRANCH: main
        run: |
          COMMIT_HASH=$(curl -s "https://api.github.com/repos/$REPO/commits/$BRANCH" | jq -r '.sha')
          if [ -z "$COMMIT_HASH" ]; then
            echo "Failed to retrieve commit hash or the result is empty."
            exit 1
          fi
          SECURE_HASH=$(echo -n "$COMMIT_HASH" | sha256sum | awk '{print $1}')
          echo "$SECURE_HASH" > ./current_hash.txt
      - name: Add and commit if changed
        id: add-and-commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'current_hash.txt'
          message: 'Update current_hash.txt'
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
  remote-dispatch:
    needs: check
    if: ${{ needs.check.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ steps.generate_token.outputs.token }}
      #     repository: ${{ vars.TARGET_REPOSITORY }}
      #     event-type: ${{ vars.TARGET_EVENT_TYPE }}
